# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  #Building Servers
  (1..3).each do |i|
    config.vm.define "srv0#1" do |srv|
      srv.vm.box = "generic/rhel8"
      srv.vm.hostname = "vm01"
      srv.vm.network :private_network, ip: "192.168.55.59"
      srv.ssh.insert_key = false
      srv.vm.synced_folder ".", "/vagrant", disabled: true
      srv.vm.disk :disk, name: "STOR", size: "3GB"
      srv.vm.provider :virtualbox do |res|
        res.memory = 512
        res.cpus = 1
      end
    end
  end
end